# version: "3.3"
# services:
#   mysql:
#     image: "mysql:8.0.21"
#     ports:
#       - "4578:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: admin
#       MYSQL_USER: test
#       MYSQL_PASSWORD: test
#       MYSQL_DATABASE: test
#   server:
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#       args:
#         - http_proxy
#         - no_proxy
#     image: "glints-test-billy/server:latest"
#     links:
#       - mysql
#     ports:
#       - "8081:8081"
#     stdin_open: true
#     tty: true

version: "3.3"
services:
  node:
    build: ./
    env_file:
      - ./.env
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - "${MYSQL_HOST}"
  db:
    build: ./db
    ports:
      - "3306:3306"
    env_file:
      - ./.env
